### ISSUE TITLE
Update nuspec with Cake Contrib Icon

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.HockeyApp#13]

**Comment by reicheltp** [comment]
@gep13 Is it ok that I use the cake icon with hockey app on top, like I have for the current preview package on NuGet, or should I use the empty cake icon?

![Cake.HockeyApp](https://raw.githubusercontent.com/cake-contrib/Cake.HockeyApp/develop/Cake.HockeyApp.png)

**Comment by gep13** [comment]
@reicheltp so, this is a sticky situation...

You are taking two icons, and stitching them together to create another one.  In theory, you are going to need sign off from both parties that this is "ok".  A logo is a trademark associated with a brand or product, and as such, may be under some form of license or copyright.  We can say easily that could allow usage of the Cake icon in this scenario, but have you requested permission from HockeyApp to use their icon in this way?

**Comment by reicheltp** [comment]
@gep13 You're right! I've not thought about this. Just cribbed the idea from other Cake Addins on NuGet. I'll update the packages this week.

**Comment by gep13** [comment]
Yip, there are a few packages that use a similar approach, and I have it on my list to talk to them too 😄 

For now, we don't actually have the Cake Contrib Icon ready to go.  @patriksvensson is working on it, so for now, there is nothing really that needs to be done, I was just adding this issue as a reminder to complete once the icon is ready.

**Comment by gep13** [comment]
Thanks again for creating this Cake Addin, we really appreciate the effort that you have put in to creating it.  

We, the Cake Team, recently announced a new Cake Contrib Icon, details of which can be found here:

http://cakebuild.net/blog/2017/06/new-cake-contrib-icon

Would you consider changing the nuspec file for your NuGet Package to use this new Cake Contrib Icon?  If so, the recommended URL to use is:

https://cdn.rawgit.com/cake-contrib/graphics/a5cf0f881c390650144b2243ae551d5b9f836196/png/cake-contrib-medium.png

Details of the above URL can be found in the repository here:

https://github.com/cake-contrib/graphics

Please let me know if you have any questions.
