### ISSUE TITLE
Cake.HockeyApp does not work anymore with actual Cake (0.19.1)

### ISSUE THREAD

**Issue by anrichter** [cake-contrib/Cake.HockeyApp#16]
Unfortunateley the plugin does not work anymore with Cake version 0.19.1. I become the following error:

    Error: The assembly 'Cake.HockeyApp, Version=0.2.3.0, Culture=neutral, PublicKeyToken=null' 
    is referencing an older version of Cake.Core (0.7.0). 
    This assembly need to reference at least Cake.Core version 0.16.0. 
    Another option is to downgrade Cake to an earlier version.

How can i fix this problem? 

Thanks for your help
Andreas

**Comment by gep13** [comment]
@anrichter yip, this is a known issue, which I am working on fixing.

For now, you could pin to an earlier version of Cake in your packages.config file.

**Comment by anrichter** [comment]
Hi @gep13 
Thank you for your quick response. I'll pin to cake 0.17.0 and it works so far.

**Comment by WebDucer** [comment]
Pinning on version 17 is not a solution on my side, becouse of use of some new features from Cake 0.19.

**Comment by jrgcubano** [comment]
The same here! Trying to use the last version of cake!

**Comment by gep13** [comment]
This has now been tested on Cake 0.20.0 and is known to work correctly, after some limited testing.
