### ISSUE TITLE
Upload Dsym to Hockey App not working 

### ISSUE THREAD

**Issue by DavidPearson01** [cake-contrib/Cake.HockeyApp#27]
Line 104 in the hockey app client is checking the wrong file for extension validity

fix 
 if (symbolFile != null)
            {
                var isSupportedSymbols = symbolFile.FullPath.EndsWith(".dsym.zip")
                                         || symbolFile.FullPath.EndsWith("mapping.txt");

                if (!isSupportedSymbols)
                {
                    throw new ArgumentException(
                        "Symbols file needs to be of the following type: *.dsym.zip for iOS / OS X, or mapping.txt file for Android.",
                        nameof(symbolFile));
                }
            }

**Comment by gep13** [comment]
@DavidPearson01 Thank you for raising this.  I have applied the change that you have mentioned in this issue here.

**Comment by gep13** [comment]
@DavidPearson01 I have just pushed out a new version of this addin with the changes that you suggested, can you please let me know if this corrects the problem that you were seeing.
