### ISSUE TITLE
Missing reference to System.Net.Http ?

### ISSUE THREAD

**Issue by MikaelStalvik** [cake-contrib/Cake.HockeyApp#38]
I'm using the most recent version of Cake, 0.22.2, and as when the build script is precompiling, I'm met with the following error message:

Could not load C:\dev\MyProject\_build\tools\Addins\cake.hockeyapp\Cake.HockeyApp\lib\net46\Cake.HockeyApp.dll (missing System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
Compiling build script...
Cake.exe : Error: Error occurred when compiling build script: C:/dev/MyProject/_build/build.cake(175,13): error CS0103: The name 'UploadToHockeyApp' does not exist in the current context

I have both .NET 4.6.1/4.7 and .NET Core 2 installed on my system

**Comment by RLittlesII** [comment]
I encountered this issue this evening.  There is a missing dependency from the net46 target.  As part of targeting Cake 0.22, I bumped the .NET Framework target to 4.6 and I apparently missed a dependency.  I'll get a fix out for this soon.

**Comment by RLittlesII** [comment]
@MikaelStalvik Are you in a position to verify the fix for this?  I loaded the package source [here](https://www.myget.org/feed/rlittlesii/package/nuget/Cake.HockeyApp).

**Comment by MikaelStalvik** [comment]
@RLittlesII Thanks for the update! The new version seems to work well!

**Comment by RLittlesII** [comment]
@MikaelStalvik I am merging this branch in now, nuget package with the resolution will be available shortly.  Thanks for the assist!
