### ISSUE TITLE
Doesn't work on Mac

### ISSUE THREAD

**Issue by rogerwcpt** [cake-contrib/Cake.HockeyApp#41]
Error is this:  

Could not find any assemblies compatible with .NETFramework,Version=v4.5.
Error: Failed to install addin 'Cake.HockeyApp'.

**Comment by devlead** [comment]
Likely you're using an older version of Cake, try pinning to version 0.6.0 of Cake.HockeyApp or upgrade to newer version of Cake

Read more about version pinning at :
https://cakebuild.net/docs/tutorials/pinning-cake-version

**Comment by RLittlesII** [comment]
@rogerwcpt Pinning your Cake version and the addin version is recommended.
version 0.7.0 moved to .NET 4.6 so it could target Cake 0.22.0.

**Comment by rogerwcpt** [comment]
Thanks that worked.
